"""codat_platform.models.operations.create_connection — re-export of the create_connection operation envelope."""

from codat_platform.api.connections import CreateConnectionRequest
from codat_platform.models.create_connection_request import CreateConnectionRequest as CreateConnectionRequestBody
from codat_platform.models.create_connection_request import CreateConnectionRequestTypedDict as CreateConnectionRequestBodyTypedDict
from codat_platform.api.connections import CreateConnectionRequestTypedDict
