"""codat_platform.models.operations.get_custom_data_type_configuration — re-export of the get_custom_data_type_configuration operation envelope."""

from codat_platform.api.custom_data_type import GetCustomDataTypeConfigurationRequest
from codat_platform.api.custom_data_type import GetCustomDataTypeConfigurationRequestTypedDict
