"""codat_platform.models.operations.get_connection_management_access_token — re-export of the get_connection_management_access_token operation envelope."""

from codat_platform.api.connection_management import GetConnectionManagementAccessTokenRequest
from codat_platform.api.connection_management import GetConnectionManagementAccessTokenRequestTypedDict
