"""codat_platform.models.operations.get_create_update_model_options_by_data_type — re-export of the get_create_update_model_options_by_data_type operation envelope."""

from codat_platform.api.push_data import GetCreateUpdateModelOptionsByDataTypeRequest
from codat_platform.api.push_data import GetCreateUpdateModelOptionsByDataTypeRequestTypedDict
