"""codat_platform.models.operations.set_company_syncsettings — re-export of the set_company_syncsettings operation envelope."""

from codat_platform.api.companies import SetCompanySyncSettingsRequest
from codat_platform.models.set_company_sync_settings_request import SetCompanySyncSettingsRequest as SetCompanySyncSettingsRequestBody
from codat_platform.models.set_company_sync_settings_request import SetCompanySyncSettingsRequestTypedDict as SetCompanySyncSettingsRequestBodyTypedDict
from codat_platform.api.companies import SetCompanySyncSettingsRequestTypedDict
