"""codat_platform.models.operations.update_profile_syncsettings — re-export of the update_profile_syncsettings operation envelope."""

from codat_platform.models.update_profile_sync_settings_request import UpdateProfileSyncSettingsRequestBody
from codat_platform.api.settings import UpdateProfileSyncSettingsRequestBodyTypedDict
