"""codat_sync_for_payables.models.operations.get_mapping_options_payments — re-export of the get_mapping_options_payments operation envelope."""

from codat_sync_for_payables.api.bill_payments import GetMappingOptionsPaymentsRequest
from codat_sync_for_payables.api.bill_payments import GetMappingOptionsPaymentsRequestTypedDict
