"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from codat_accounting.types import BaseModel
from enum import Enum
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class SalesOrderRefDataType(str, Enum):
    r"""The underlying data type associated to the reference `id`."""

    SALES_ORDERS = "salesOrders"


class SalesOrderRefTypedDict(TypedDict):
    data_type: NotRequired[SalesOrderRefDataType]
    r"""The underlying data type associated to the reference `id`."""
    id: NotRequired[str]
    r"""Unique identifier to a record in `dataType`."""


class SalesOrderRef(BaseModel):
    data_type: Annotated[
        Optional[SalesOrderRefDataType], pydantic.Field(alias="dataType")
    ] = None
    r"""The underlying data type associated to the reference `id`."""

    id: Optional[str] = None
    r"""Unique identifier to a record in `dataType`."""
