"""codat_sync_for_expenses.models.operations.create_connection — re-export of the create_connection operation envelope."""

from codat_sync_for_expenses.api.connections import CreateConnectionRequest
from codat_sync_for_expenses.models.create_connection_request import CreateConnectionRequest as CreateConnectionRequestBody
from codat_sync_for_expenses.models.create_connection_request import CreateConnectionRequestTypedDict as CreateConnectionRequestBodyTypedDict
from codat_sync_for_expenses.api.connections import CreateConnectionRequestTypedDict
