"""codat_sync_for_expenses.models.operations.create_partner_expense_connection — re-export of the create_partner_expense_connection operation envelope."""

from codat_sync_for_expenses.api.connections import CreatePartnerExpenseConnectionRequest
from codat_sync_for_expenses.api.connections import CreatePartnerExpenseConnectionRequestTypedDict
