"""codat_sync_for_expenses.models.operations.get_create_bankaccounts_model — re-export of the get_create_bankaccounts_model operation envelope."""

from codat_sync_for_expenses.api.bank_accounts import GetCreateBankAccountsModelRequest
from codat_sync_for_expenses.api.bank_accounts import GetCreateBankAccountsModelRequestTypedDict
