"""codat_sync_for_expenses.models.operations.update_reimbursable_expense_transaction — re-export of the update_reimbursable_expense_transaction operation envelope."""

from codat_sync_for_expenses.api.reimbursements import UpdateReimbursableExpenseTransactionRequest
from codat_sync_for_expenses.api.reimbursements import UpdateReimbursableExpenseTransactionRequestTypedDict
