"""codat_lending.models.operations.create_connection — re-export of the create_connection operation envelope."""

from codat_lending.api.connections import CreateConnectionRequest
from codat_lending.models.create_connection_request import CreateConnectionRequest as CreateConnectionRequestBody
from codat_lending.models.create_connection_request import CreateConnectionRequestTypedDict as CreateConnectionRequestBodyTypedDict
from codat_lending.api.connections import CreateConnectionRequestTypedDict
