"""codat_lending.models.operations.download_accounting_direct_income_attachment — re-export of the download_accounting_direct_income_attachment operation envelope."""

from codat_lending.api.direct_incomes import DownloadAccountingDirectIncomeAttachmentRequest
from codat_lending.api.direct_incomes import DownloadAccountingDirectIncomeAttachmentRequestTypedDict
