"""codat_lending.models.operations.download_accounting_supplier_attachment — re-export of the download_accounting_supplier_attachment operation envelope."""

from codat_lending.api.suppliers import DownloadAccountingSupplierAttachmentRequest
from codat_lending.api.suppliers import DownloadAccountingSupplierAttachmentRequestTypedDict
