"""codat_lending.models.operations.download_accounting_customer_attachment — re-export of the download_accounting_customer_attachment operation envelope."""

from codat_lending.api.customers import DownloadAccountingCustomerAttachmentRequest
from codat_lending.api.customers import DownloadAccountingCustomerAttachmentRequestTypedDict
