"""codat_lending.models.operations.download_accounting_invoice_attachment — re-export of the download_accounting_invoice_attachment operation envelope."""

from codat_lending.api.invoices import DownloadAccountingInvoiceAttachmentRequest
from codat_lending.api.invoices import DownloadAccountingInvoiceAttachmentRequestTypedDict
