"""codat_lending.models.operations.get_accounting_direct_income_attachment — re-export of the get_accounting_direct_income_attachment operation envelope."""

from codat_lending.api.direct_incomes import GetAccountingDirectIncomeAttachmentRequest
from codat_lending.api.direct_incomes import GetAccountingDirectIncomeAttachmentRequestTypedDict
