"""codat_lending.models.operations.get_create_update_bankaccounts_model — re-export of the get_create_update_bankaccounts_model operation envelope."""

from codat_lending.api.bank_accounts import GetCreateUpdateBankAccountsModelRequest
from codat_lending.api.bank_accounts import GetCreateUpdateBankAccountsModelRequestTypedDict
