"""codat_lending.models.operations.get_banking_transaction_category — re-export of the get_banking_transaction_category operation envelope."""

from codat_lending.api.transaction_categories import GetBankingTransactionCategoryRequest
from codat_lending.api.transaction_categories import GetBankingTransactionCategoryRequestTypedDict
