"""codat_lending.models.operations.get_categorized_profit_and_loss_statement — re-export of the get_categorized_profit_and_loss_statement operation envelope."""

from codat_lending.api.profit_and_loss import GetCategorizedProfitAndLossStatementRequest
from codat_lending.api.profit_and_loss import GetCategorizedProfitAndLossStatementRequestTypedDict
