"""codat_lending.models.operations.get_create_chartofaccounts_model — re-export of the get_create_chartofaccounts_model operation envelope."""

from codat_lending.api.loan_writeback_accounts import GetCreateChartOfAccountsModelRequest
from codat_lending.api.loan_writeback_accounts import GetCreateChartOfAccountsModelRequestTypedDict
