"""codat_lending.models.operations.get_accounting_account_transaction — re-export of the get_accounting_account_transaction operation envelope."""

from codat_lending.api.account_transactions import GetAccountingAccountTransactionRequest
from codat_lending.api.account_transactions import GetAccountingAccountTransactionRequestTypedDict
