"""codat_lending.models.operations.get_bank_statement_upload_configuration — re-export of the get_bank_statement_upload_configuration operation envelope."""

from codat_lending.api.bank_statements import GetBankStatementUploadConfigurationRequest
from codat_lending.api.bank_statements import GetBankStatementUploadConfigurationRequestTypedDict
