"""codat_lending.models.operations.get_create_update_suppliers_model — re-export of the get_create_update_suppliers_model operation envelope."""

from codat_lending.api.loan_writeback_suppliers import GetCreateUpdateSuppliersModelRequest
from codat_lending.api.loan_writeback_suppliers import GetCreateUpdateSuppliersModelRequestTypedDict
