"""codat_lending.models.operations.get_create_bank_transactions_model — re-export of the get_create_bank_transactions_model operation envelope."""

from codat_lending.api.bank_transactions import GetCreateBankTransactionsModelRequest
from codat_lending.api.bank_transactions import GetCreateBankTransactionsModelRequestTypedDict
