"""codat_lending.models.operations.list_accounting_direct_income_attachments — re-export of the list_accounting_direct_income_attachments operation envelope."""

from codat_lending.api.direct_incomes import ListAccountingDirectIncomeAttachmentsRequest
from codat_lending.api.direct_incomes import ListAccountingDirectIncomeAttachmentsRequestTypedDict
