"""codat_lending.models.operations.set_bank_statement_upload_configuration — re-export of the set_bank_statement_upload_configuration operation envelope."""

from codat_lending.api.bank_statements import SetBankStatementUploadConfigurationRequest
from codat_lending.api.bank_statements import SetBankStatementUploadConfigurationRequestTypedDict
