"""codat_lending.models.operations.start_bank_statement_upload_session — re-export of the start_bank_statement_upload_session operation envelope."""

from codat_lending.api.bank_statements import StartBankStatementUploadSessionRequest
from codat_lending.api.bank_statements import StartBankStatementUploadSessionRequestTypedDict
