"""Generated wrapper exposing the banking sub-method-groups.

Generated by pipeline/postprocess_generated.py — do not edit by hand.
"""

from __future__ import annotations

from codat_lending.api_client import ApiClient

from codat_lending.api.account_balances import AccountBalances
from codat_lending.api.banking_accounts import BankingAccounts
from codat_lending.api.categorized_statement import CategorizedStatement
from codat_lending.api.transaction_categories import TransactionCategories
from codat_lending.api.transactions import Transactions


class Banking:
    account_balances: AccountBalances
    accounts: BankingAccounts
    categorized_statement: CategorizedStatement
    transaction_categories: TransactionCategories
    transactions: Transactions

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client
        self.account_balances = AccountBalances(api_client=self.api_client)
        self.accounts = BankingAccounts(api_client=self.api_client)
        self.categorized_statement = CategorizedStatement(api_client=self.api_client)
        self.transaction_categories = TransactionCategories(api_client=self.api_client)
        self.transactions = Transactions(api_client=self.api_client)
