"""Generated wrapper exposing the loan-writeback sub-method-groups.

Generated by pipeline/postprocess_generated.py — do not edit by hand.
"""

from __future__ import annotations

from codat_lending.api_client import ApiClient

from codat_lending.api.loan_writeback_accounts import LoanWritebackAccounts
from codat_lending.api.bank_accounts import BankAccounts
from codat_lending.api.bank_transactions import BankTransactions
from codat_lending.api.create_operations import CreateOperations
from codat_lending.api.direct_costs import DirectCosts
from codat_lending.api.loan_writeback_payments import LoanWritebackPayments
from codat_lending.api.source_accounts import SourceAccounts
from codat_lending.api.loan_writeback_suppliers import LoanWritebackSuppliers
from codat_lending.api.transfers import Transfers


class LoanWriteback:
    accounts: LoanWritebackAccounts
    bank_accounts: BankAccounts
    bank_transactions: BankTransactions
    create_operations: CreateOperations
    direct_costs: DirectCosts
    payments: LoanWritebackPayments
    source_accounts: SourceAccounts
    suppliers: LoanWritebackSuppliers
    transfers: Transfers

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client
        self.accounts = LoanWritebackAccounts(api_client=self.api_client)
        self.bank_accounts = BankAccounts(api_client=self.api_client)
        self.bank_transactions = BankTransactions(api_client=self.api_client)
        self.create_operations = CreateOperations(api_client=self.api_client)
        self.direct_costs = DirectCosts(api_client=self.api_client)
        self.payments = LoanWritebackPayments(api_client=self.api_client)
        self.source_accounts = SourceAccounts(api_client=self.api_client)
        self.suppliers = LoanWritebackSuppliers(api_client=self.api_client)
        self.transfers = Transfers(api_client=self.api_client)
