# coding: utf-8

"""
    Platform API

    An API for the common components of all of Codat's products.  These end points cover creating and managing your companies, data connections, and integrations.  [Read about the building blocks of Codat...](https://docs.codat.io/core-concepts/companies) | [See our OpenAPI spec](https://github.com/codatio/oas)   --- <!-- Start Codat Tags Table --> ## Endpoints  | Endpoints | Description | | :- |:- | | Companies | Create and manage your SMB users' companies. | | Connections | Create new and manage existing data connections for a company. | | Connection management | Configure connection management UI and retrieve access tokens for authentication. | | Webhooks | Create and manage webhooks that listen to Codat's events. | | Integrations | Get a list of integrations supported by Codat and their logos. | | Refresh data | Initiate data refreshes, view pull status and history. | | Settings | Manage company profile configuration, sync settings, and API keys. | | Push data | Initiate and monitor Create, Update, and Delete operations. | | Supplemental data | Configure and pull additional data you can include in Codat's standard data types. | | Custom data type | Configure and pull additional data types that are not included in Codat's standardized data model. | <!-- End Codat Tags Table -->

    The version of the OpenAPI document: 3.0.0
    Contact: support@codat.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, model_serializer
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from codat_platform.models.shared.pushoptionchoice import PushOptionChoice, PushOptionChoiceTypedDict
from codat_platform.models.shared.pushoptionproperty import PushOptionProperty, PushOptionPropertyTypedDict
from codat_platform.models.shared.pushoptiontype import PushOptionType
from codat_platform.models.shared.pushvalidationinfo import PushValidationInfo, PushValidationInfoTypedDict
from typing import Optional, Set
from typing_extensions import Self

from codat_platform.types import OptionalNullable, UNSET, UNSET_SENTINEL
class PushOption(BaseModel):

    @model_serializer(mode="wrap")
    def _serialize_drop_none(self, handler):
        serialized = handler(self)
        _nullable = {'options', 'properties'}
        return {
            k: v for k, v in serialized.items()
            if v != UNSET_SENTINEL and (v is not None or k in _nullable)
        }
    """
    PushOption
    """ # noqa: E501
    type: PushOptionType
    display_name: str = Field(description="The property's display name.", alias="displayName")
    description: Optional[str] = Field(default=None, description="A description of the property.")
    required: bool = Field(description="The property is required if `True`.")
    properties: OptionalNullable[Dict[str, PushOptionProperty]] = UNSET
    options: OptionalNullable[List[PushOptionChoice]] = UNSET
    validation: Optional[PushValidationInfo] = None
    __properties: ClassVar[List[str]] = ["type", "displayName", "description", "required", "properties", "options", "validation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PushOption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in properties (dict)
        _field_dict = {}
        if self.properties:
            for _key_properties in self.properties:
                if self.properties[_key_properties]:
                    _field_dict[_key_properties] = self.properties[_key_properties].to_dict()
            _dict['properties'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # override the default output from pydantic by calling `to_dict()` of validation
        if self.validation:
            _dict['validation'] = self.validation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PushOption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "displayName": obj.get("displayName"),
            "description": obj.get("description"),
            "required": obj.get("required"),
            "properties": dict(
                (_k, PushOptionProperty.from_dict(_v))
                for _k, _v in obj["properties"].items()
            )
            if obj.get("properties") is not None
            else None,
            "options": [PushOptionChoice.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "validation": PushValidationInfo.from_dict(obj["validation"]) if obj.get("validation") is not None else None
        })
        return _obj





class PushOptionTypedDict(TypedDict):
    """TypedDict variant of PushOption, for dict-literal request/response inputs."""
    type: PushOptionType
    display_name: NotRequired[str]
    description: NotRequired[Optional[str]]
    required: NotRequired[bool]
    properties: NotRequired[Optional[Dict[str, PushOptionPropertyTypedDict]]]
    options: NotRequired[Optional[List[PushOptionChoiceTypedDict]]]
    validation: NotRequired[Optional[PushValidationInfoTypedDict]]
