"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import accountingbillpayment as shared_accountingbillpayment
from typing import Optional


@dataclasses.dataclass
class GetAccountingBillPaymentRequest:
    bill_payment_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'billPaymentId', 'style': 'simple', 'explode': False }})
    r"""Unique identifier for a bill payment."""
    company_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'companyId', 'style': 'simple', 'explode': False }})
    r"""Unique identifier for a company."""
    



@dataclasses.dataclass
class GetAccountingBillPaymentResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    accounting_bill_payment: Optional[shared_accountingbillpayment.AccountingBillPayment] = dataclasses.field(default=None)
    r"""Success"""
    

