[project]
name = "codat-lending"
version = "11.0.2"
description = "Make credit decisions backed by enhanced financials, metrics, reports, and data integrity features."
authors = [{ name = "Codat", email = "support@codat.io" }]
readme = "README-PYPI.md"
requires-python = ">=3.10"
dependencies = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
    "httpx >= 0.28.1",
    "httpcore >= 1.0.9",
]

[project.urls]
Repository = "https://github.com/codatio/client-sdk-python.git"

[tool.poetry]
packages = [
    { include = "codat_lending", from = "src" },
]
include = ["src/codat_lending/py.typed"]

[tool.poetry.group.dev.dependencies]
pytest = ">=7.2.1"
mypy = ">=1.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
