"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from codat_lending.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from codat_lending.utils import serialize_decimal, validate_decimal
from decimal import Decimal
from pydantic import model_serializer
from pydantic.functional_serializers import PlainSerializer
from pydantic.functional_validators import BeforeValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AccountBalanceAmountsTypedDict(TypedDict):
    r"""Depending on the data provided by the underlying bank, not all balances are always available."""

    available: NotRequired[Nullable[Decimal]]
    r"""The balance available in the account, including any pending transactions. This doesn't include additional funds available from any overdrafts."""
    current: NotRequired[Decimal]
    r"""The balance of the account only including cleared transactions."""
    limit: NotRequired[Nullable[Decimal]]
    r"""The minimum allowed balance for the account. For example, a $100.00 overdraft would show as a limit of `-100.00`."""


class AccountBalanceAmounts(BaseModel):
    r"""Depending on the data provided by the underlying bank, not all balances are always available."""

    available: Annotated[
        OptionalNullable[Decimal],
        BeforeValidator(validate_decimal),
        PlainSerializer(serialize_decimal(False)),
    ] = UNSET
    r"""The balance available in the account, including any pending transactions. This doesn't include additional funds available from any overdrafts."""

    current: Annotated[
        Optional[Decimal],
        BeforeValidator(validate_decimal),
        PlainSerializer(serialize_decimal(False)),
    ] = None
    r"""The balance of the account only including cleared transactions."""

    limit: Annotated[
        OptionalNullable[Decimal],
        BeforeValidator(validate_decimal),
        PlainSerializer(serialize_decimal(False)),
    ] = UNSET
    r"""The minimum allowed balance for the account. For example, a $100.00 overdraft would show as a limit of `-100.00`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["available", "current", "limit"])
        nullable_fields = set(["available", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
