"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from codat_lending.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EndUploadSessionRequestStatus(str, Enum):
    r"""An indicator to cancel the dataset processing or trigger ingestion and enrichment of data."""

    CANCEL = "Cancel"
    PROCESS = "Process"


class EndUploadSessionRequestTypedDict(TypedDict):
    status: NotRequired[EndUploadSessionRequestStatus]
    r"""An indicator to cancel the dataset processing or trigger ingestion and enrichment of data."""


class EndUploadSessionRequest(BaseModel):
    status: Optional[EndUploadSessionRequestStatus] = None
    r"""An indicator to cancel the dataset processing or trigger ingestion and enrichment of data."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
