from __future__ import annotations

from codat_lending.models.record_line_reference import RecordLineReference as BillLineItemPurchaseOrderLineRef, RecordLineReferenceTypedDict as BillLineItemPurchaseOrderLineRefTypedDict

__all__ = ["BillLineItemPurchaseOrderLineRef", "BillLineItemPurchaseOrderLineRefTypedDict"]
