"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .companyreference import CompanyReference, CompanyReferenceTypedDict
from .transaction import Transaction, TransactionTypedDict
from codat_sync_for_expenses.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ExpensesSyncWebhookPayloadTypedDict(TypedDict):
    reference_company: NotRequired[CompanyReferenceTypedDict]
    sync_id: NotRequired[str]
    r"""Unique identifier of the sync."""
    transactions: NotRequired[List[TransactionTypedDict]]


class ExpensesSyncWebhookPayload(BaseModel):
    reference_company: Annotated[
        Optional[CompanyReference], pydantic.Field(alias="referenceCompany")
    ] = None

    sync_id: Annotated[Optional[str], pydantic.Field(alias="syncId")] = None
    r"""Unique identifier of the sync."""

    transactions: Optional[List[Transaction]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["referenceCompany", "syncId", "transactions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ExpensesSyncWebhookPayload.model_rebuild()
except NameError:
    pass
