"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from codat_sync_for_expenses.types import BaseModel
from enum import Enum
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TrackingRefDataType(str, Enum):
    r"""The type of the linked reference"""

    TRACKING_CATEGORIES = "trackingCategories"
    CUSTOMERS = "customers"


class TrackingRefTypedDict(TypedDict):
    data_type: NotRequired[TrackingRefDataType]
    r"""The type of the linked reference"""
    id: NotRequired[str]
    r"""Unique identifier of the linked reference from mapping options or the unique identifier of the linked customer."""


class TrackingRef(BaseModel):
    data_type: Annotated[
        Optional[TrackingRefDataType], pydantic.Field(alias="dataType")
    ] = TrackingRefDataType.TRACKING_CATEGORIES
    r"""The type of the linked reference"""

    id: Optional[str] = None
    r"""Unique identifier of the linked reference from mapping options or the unique identifier of the linked customer."""
