"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sourceaccountv2 import SourceAccountV2, SourceAccountV2TypedDict
from codat_bankfeeds.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SourceAccountV2BatchCreateResultTypedDict(TypedDict):
    r"""Status details and corresponding object of the `Create account` operation."""

    account: NotRequired[SourceAccountV2TypedDict]
    r"""The target bank account in a supported accounting software for ingestion into a bank feed."""
    error: NotRequired[Nullable[str]]
    r"""A brief description of the error."""
    status_code: NotRequired[int]
    r"""The HTTP status code for the creation of the source account"""


class SourceAccountV2BatchCreateResult(BaseModel):
    r"""Status details and corresponding object of the `Create account` operation."""

    account: Optional[SourceAccountV2] = None
    r"""The target bank account in a supported accounting software for ingestion into a bank feed."""

    error: OptionalNullable[str] = UNSET
    r"""A brief description of the error."""

    status_code: Annotated[Optional[int], pydantic.Field(alias="statusCode")] = None
    r"""The HTTP status code for the creation of the source account"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account", "error", "statusCode"])
        nullable_fields = set(["error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
