"""codat_lending.codatlending_financial_statements_accounts — re-export of the codatlending_financial_statements_accounts method group."""

from codat_lending.api.financial_statements_accounts import FinancialStatementsAccounts as CodatLendingFinancialStatementsAccounts
