"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from codat_lending.balance_sheet import BalanceSheet
from codat_lending.cash_flow import CashFlow
from codat_lending.codatlending_financial_statements_accounts import (
    CodatLendingFinancialStatementsAccounts,
)
from codat_lending.profit_and_loss import ProfitAndLoss
from typing import Optional


class FinancialStatements(BaseSDK):
    accounts: CodatLendingFinancialStatementsAccounts
    balance_sheet: BalanceSheet
    cash_flow: CashFlow
    profit_and_loss: ProfitAndLoss

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.accounts = CodatLendingFinancialStatementsAccounts(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.balance_sheet = BalanceSheet(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.cash_flow = CashFlow(self.sdk_configuration, parent_ref=self.parent_ref)
        self.profit_and_loss = ProfitAndLoss(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
