# coding: utf-8

"""
    Bill pay (synchronous solution)

    The API reference for the synchronous Bill Pay solution.   The synchronous Bill Pay solution is an API and a set of supporting tools designed to integrate a bill pay flow into your app as quickly as possible. It's ideal for facilitating essential bill payment processes within your SMB's accounting software.  [Explore solution](https://docs.codat.io/payables/overview) | [See OpenAPI spec](https://github.com/codatio/oas)  --- ## Supported Integrations  | Integration                   | Supported | |-------------------------------|-----------| | FreeAgent                     | Yes       | | QuickBooks Online             | Yes       | | Oracle NetSuite               | Yes       | | Sage Intacct                  | Yes       | | Xero                          | Yes       | | Zoho Books                    | Yes       |  --- <!-- Start Codat Tags Table --> ## Endpoints  | Endpoints | Description | | :- |:- | | Companies | Create and manage your SMB users' companies. | | Connections | Create new and manage existing data connections for a company. | | Company information | View company profile from the source platform. | | Bills | Get, create, and update Bills. | | Bill payments | Get, create, and update Bill payments. | | Suppliers | Get, create, and update Suppliers. | | Bank accounts | Create a bank account for a given company's connection. | <!-- End Codat Tags Table -->

    The version of the OpenAPI document: 3.0.0
    Contact: support@codat.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from codat_sync_for_payables.models.data_type import DataType
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_serializer
from typing import Any, ClassVar, Dict, List, Optional
from codat_sync_for_payables.models.push_operation_change import PushOperationChange, PushOperationChangeTypedDict
from codat_sync_for_payables.models.push_operation_status import PushOperationStatus
from codat_sync_for_payables.models.validation import Validation, ValidationTypedDict
from typing import Optional, Set
from typing_extensions import Self, NotRequired, TypedDict

class PushOperation(BaseModel):

    @model_serializer(mode="wrap")
    def _serialize_drop_none(self, handler):
        serialized = handler(self)
        return {k: v for k, v in serialized.items() if v is not None}
    """
    PushOperation
    """ # noqa: E501
    changes: Optional[List[PushOperationChange]] = Field(default=None, description="Contains a single entry that communicates which record has changed and the manner in which it changed. ")
    data_type: Optional[str] = Field(default=None, description="Available data types", alias="dataType")
    company_id: str = Field(description="Unique identifier for your SMB in Codat.", alias="companyId")
    push_operation_key: str = Field(description="A unique identifier generated by Codat to represent this single push operation. This identifier can be used to track the status of the push, and should be persisted.", alias="pushOperationKey")
    data_connection_key: str = Field(description="Unique identifier for a company's data connection.", alias="dataConnectionKey")
    requested_on_utc: str = Field(description="In Codat's data model, dates and times are represented using the <a class=\"external\" href=\"https://en.wikipedia.org/wiki/ISO_8601\" target=\"_blank\">ISO 8601 standard</a>. Date and time fields are formatted as strings; for example:  ``` 2020-10-08T22:40:50Z 2021-01-01T00:00:00 ```    When syncing data that contains `DateTime` fields from Codat, make sure you support the following cases when reading time information:  - Coordinated Universal Time (UTC): `2021-11-15T06:00:00Z` - Unqualified local time: `2021-11-15T01:00:00` - UTC time offsets: `2021-11-15T01:00:00-05:00`  > Time zones >  > Not all dates from Codat will contain information about time zones.   > Where it is not available from the underlying platform, Codat will return these as times local to the business whose data has been synced.", alias="requestedOnUtc")
    completed_on_utc: Optional[str] = Field(default=None, description="In Codat's data model, dates and times are represented using the <a class=\"external\" href=\"https://en.wikipedia.org/wiki/ISO_8601\" target=\"_blank\">ISO 8601 standard</a>. Date and time fields are formatted as strings; for example:  ``` 2020-10-08T22:40:50Z 2021-01-01T00:00:00 ```    When syncing data that contains `DateTime` fields from Codat, make sure you support the following cases when reading time information:  - Coordinated Universal Time (UTC): `2021-11-15T06:00:00Z` - Unqualified local time: `2021-11-15T01:00:00` - UTC time offsets: `2021-11-15T01:00:00-05:00`  > Time zones >  > Not all dates from Codat will contain information about time zones.   > Where it is not available from the underlying platform, Codat will return these as times local to the business whose data has been synced.", alias="completedOnUtc")
    timeout_in_minutes: Optional[int] = Field(default=None, description="Number of minutes the push operation must complete within before it times out.", alias="timeoutInMinutes")
    timeout_in_seconds: Optional[int] = Field(default=None, description="Number of seconds the push operation must complete within before it times out.", alias="timeoutInSeconds")
    status: PushOperationStatus
    error_message: Optional[str] = Field(default=None, description="A message about the error.", alias="errorMessage")
    validation: Optional[Validation] = None
    status_code: int = Field(description="Push status code.", alias="statusCode")
    __properties: ClassVar[List[str]] = ["changes", "dataType", "companyId", "pushOperationKey", "dataConnectionKey", "requestedOnUtc", "completedOnUtc", "timeoutInMinutes", "timeoutInSeconds", "status", "errorMessage", "validation", "statusCode"]

    @field_validator('data_type')
    def data_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['accountTransactions', 'balanceSheet', 'bankAccounts', 'bankTransactions', 'billCreditNotes', 'billPayments', 'bills', 'cashFlowStatement', 'chartOfAccounts', 'company', 'creditNotes', 'customers', 'directCosts', 'directIncomes', 'invoices', 'itemReceipts', 'items', 'journalEntries', 'journals', 'paymentMethods', 'payments', 'profitAndLoss', 'purchaseOrders', 'salesOrders', 'suppliers', 'taxRates', 'trackingCategories', 'transfers', 'banking-accountBalances', 'banking-accounts', 'banking-transactionCategories', 'banking-transactions', 'commerce-companyInfo', 'commerce-customers', 'commerce-disputes', 'commerce-locations', 'commerce-orders', 'commerce-paymentMethods', 'commerce-payments', 'commerce-productCategories', 'commerce-products', 'commerce-taxComponents', 'commerce-transactions']):
            raise ValueError("must be one of enum values ('accountTransactions', 'balanceSheet', 'bankAccounts', 'bankTransactions', 'billCreditNotes', 'billPayments', 'bills', 'cashFlowStatement', 'chartOfAccounts', 'company', 'creditNotes', 'customers', 'directCosts', 'directIncomes', 'invoices', 'itemReceipts', 'items', 'journalEntries', 'journals', 'paymentMethods', 'payments', 'profitAndLoss', 'purchaseOrders', 'salesOrders', 'suppliers', 'taxRates', 'trackingCategories', 'transfers', 'banking-accountBalances', 'banking-accounts', 'banking-transactionCategories', 'banking-transactions', 'commerce-companyInfo', 'commerce-customers', 'commerce-disputes', 'commerce-locations', 'commerce-orders', 'commerce-paymentMethods', 'commerce-payments', 'commerce-productCategories', 'commerce-products', 'commerce-taxComponents', 'commerce-transactions')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PushOperation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in changes (list)
        _items = []
        if self.changes:
            for _item_changes in self.changes:
                if _item_changes:
                    _items.append(_item_changes.to_dict())
            _dict['changes'] = _items
        # override the default output from pydantic by calling `to_dict()` of validation
        if self.validation:
            _dict['validation'] = self.validation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PushOperation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "changes": [PushOperationChange.from_dict(_item) for _item in obj["changes"]] if obj.get("changes") is not None else None,
            "dataType": obj.get("dataType"),
            "companyId": obj.get("companyId"),
            "pushOperationKey": obj.get("pushOperationKey"),
            "dataConnectionKey": obj.get("dataConnectionKey"),
            "requestedOnUtc": obj.get("requestedOnUtc"),
            "completedOnUtc": obj.get("completedOnUtc"),
            "timeoutInMinutes": obj.get("timeoutInMinutes"),
            "timeoutInSeconds": obj.get("timeoutInSeconds"),
            "status": obj.get("status"),
            "errorMessage": obj.get("errorMessage"),
            "validation": Validation.from_dict(obj["validation"]) if obj.get("validation") is not None else None,
            "statusCode": obj.get("statusCode")
        })
        return _obj





class PushOperationTypedDict(TypedDict):
    """TypedDict variant of PushOperation, for dict-literal request/response inputs."""
    changes: NotRequired[Optional[List[PushOperationChangeTypedDict]]]
    data_type: NotRequired[Optional[str]]
    company_id: NotRequired[str]
    push_operation_key: NotRequired[str]
    data_connection_key: NotRequired[str]
    requested_on_utc: NotRequired[str]
    completed_on_utc: NotRequired[Optional[str]]
    timeout_in_minutes: NotRequired[Optional[int]]
    timeout_in_seconds: NotRequired[Optional[int]]
    status: PushOperationStatus
    error_message: NotRequired[Optional[str]]
    validation: NotRequired[Optional[ValidationTypedDict]]
    status_code: NotRequired[int]
