# coding: utf-8

# flake8: noqa
"""
    Bank Feeds

    Bank Feeds solution enables your SMB users to set up bank feeds from accounts in your application to supported accounting software.  A bank feed is a connection between a source bank account in your application and a target bank account in a supported accounting software.  [Explore solution](https://docs.codat.io/bank-feeds-api/overview) | [See OpenAPI spec](https://github.com/codatio/oas)  --- <!-- Start Codat Tags Table --> ## Endpoints  | Endpoints | Description | | :- |:- | | Companies | Create and manage your SMB users' companies. | | Connections | Create new and manage existing data connections for a company. | | Source accounts | Provide and manage lists of source bank accounts. | | Account mapping | Extra functionality for building an account management UI. | | Company information | Get detailed information about a company from the underlying platform. | | Transactions | Create new bank account transactions for a company's connections, and see previous operations. | <!-- End Codat Tags Table -->

    The version of the OpenAPI document: 3.0.0
    Contact: support@codat.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from codat_bankfeeds.models.access_token import AccessToken
from codat_bankfeeds.models.shared.accountinfo import AccountInfo
from codat_bankfeeds.models.accounting_bank_account import AccountingBankAccount
from codat_bankfeeds.models.shared.bankaccountcreateresponse import BankAccountCreateResponse
from codat_bankfeeds.models.bank_account_create_response_all_of_data import BankAccountCreateResponseAllOfData
from codat_bankfeeds.models.shared.bankaccountcredentials import BankAccountCredentials
from codat_bankfeeds.models.shared.bankaccountprototype import BankAccountPrototype
from codat_bankfeeds.models.shared.bankaccountstatus import BankAccountStatus
from codat_bankfeeds.models.shared.bankaccounts import BankAccounts
from codat_bankfeeds.models.shared.bankfeedaccountmapping import BankFeedAccountMapping
from codat_bankfeeds.models.shared.bankfeedaccountmappingresponse import BankFeedAccountMappingResponse
from codat_bankfeeds.models.shared.bankfeedmapping import BankFeedMapping
from codat_bankfeeds.models.bank_transaction import BankTransaction
from codat_bankfeeds.models.shared.clientratelimitwebhook import ClientRateLimitWebhook
from codat_bankfeeds.models.shared.clientratelimitwebhookpayload import ClientRateLimitWebhookPayload
from codat_bankfeeds.models.shared.companies import Companies
from codat_bankfeeds.models.shared.company import Company
from codat_bankfeeds.models.shared.companyaccesstoken import CompanyAccessToken
from codat_bankfeeds.models.company_details import CompanyDetails
from codat_bankfeeds.models.shared.companyinformation import CompanyInformation
from codat_bankfeeds.models.shared.companyreference import CompanyReference
from codat_bankfeeds.models.company_reference_links import CompanyReferenceLinks
from codat_bankfeeds.models.shared.companyrequestbody import CompanyRequestBody
from codat_bankfeeds.models.shared.companyupdaterequest import CompanyUpdateRequest
from codat_bankfeeds.models.shared.connection import Connection
from codat_bankfeeds.models.shared.connections import Connections
from codat_bankfeeds.models.shared.createbanktransactions import CreateBankTransactions
from codat_bankfeeds.models.shared.createbanktransactionsresponse import CreateBankTransactionsResponse
from codat_bankfeeds.models.create_batch_source_account201_response_inner import CreateBatchSourceAccount201ResponseInner
from codat_bankfeeds.models.create_batch_source_account207_response_inner import CreateBatchSourceAccount207ResponseInner
from codat_bankfeeds.models.create_batch_source_account_request_body import CreateBatchSourceAccountRequestBody
from codat_bankfeeds.models.create_connection_request import CreateConnectionRequest
from codat_bankfeeds.models.create_source_account200_response import CreateSourceAccount200Response
from codat_bankfeeds.models.create_source_account_request import CreateSourceAccountRequest
from codat_bankfeeds.models.shared.dataconnectionerror import DataConnectionError
from codat_bankfeeds.models.shared.dataconnectionstatus import DataConnectionStatus
from codat_bankfeeds.models.shared.datatype import DataType
from codat_bankfeeds.models.error_message import ErrorMessage
from codat_bankfeeds.models.shared.errorvalidation import ErrorValidation
from codat_bankfeeds.models.shared.errorvalidationitem import ErrorValidationItem
from codat_bankfeeds.models.shared.generateotpresponse import GenerateOtpResponse
from codat_bankfeeds.models.shared.halref import HalRef
from codat_bankfeeds.models.items import Items
from codat_bankfeeds.models.shared.links import Links
from codat_bankfeeds.models.list_source_accounts200_response import ListSourceAccounts200Response
from codat_bankfeeds.models.metadata import Metadata
from codat_bankfeeds.models.model1 import Model1
from codat_bankfeeds.models.pull_operation import PullOperation
from codat_bankfeeds.models.pull_operations import PullOperations
from codat_bankfeeds.models.shared.pushchangetype import PushChangeType
from codat_bankfeeds.models.shared.pushfieldvalidation import PushFieldValidation
from codat_bankfeeds.models.shared.pushoperation import PushOperation
from codat_bankfeeds.models.shared.pushoperationchange import PushOperationChange
from codat_bankfeeds.models.shared.pushoperationref import PushOperationRef
from codat_bankfeeds.models.shared.pushoperationstatus import PushOperationStatus
from codat_bankfeeds.models.shared.pushoperations import PushOperations
from codat_bankfeeds.models.shared.pushoption import PushOption
from codat_bankfeeds.models.shared.pushoptionchoice import PushOptionChoice
from codat_bankfeeds.models.shared.pushoptionproperty import PushOptionProperty
from codat_bankfeeds.models.shared.pushoptiontype import PushOptionType
from codat_bankfeeds.models.shared.pushvalidationinfo import PushValidationInfo
from codat_bankfeeds.models.shared.routinginfo import RoutingInfo
from codat_bankfeeds.models.shared.sourceaccount import SourceAccount
from codat_bankfeeds.models.shared.sourceaccountbatchcreateresponse import SourceAccountBatchCreateResponse
from codat_bankfeeds.models.shared.sourceaccountbatchcreateresult import SourceAccountBatchCreateResult
from codat_bankfeeds.models.shared.sourceaccountbatcherrorresponse import SourceAccountBatchErrorResponse
from codat_bankfeeds.models.source_account_batch_error_response_result import SourceAccountBatchErrorResponseResult
from codat_bankfeeds.models.shared.sourceaccountprototype import SourceAccountPrototype
from codat_bankfeeds.models.source_account_v2 import SourceAccountV2
from codat_bankfeeds.models.shared.sourceaccountv2batchcreateresponse import SourceAccountV2BatchCreateResponse
from codat_bankfeeds.models.shared.sourceaccountv2batchcreateresult import SourceAccountV2BatchCreateResult
from codat_bankfeeds.models.shared.sourceaccountv2prototype import SourceAccountV2Prototype
from codat_bankfeeds.models.shared.sourceaccountwebhook import SourceAccountWebhook
from codat_bankfeeds.models.shared.sourceaccountwebhookpayload import SourceAccountWebhookPayload
from codat_bankfeeds.models.shared.startscheduledsyncresult import StartScheduledSyncResult
from codat_bankfeeds.models.supplemental_data import SupplementalData
from codat_bankfeeds.models.shared.syncstatusresult import SyncStatusResult
from codat_bankfeeds.models.shared.targetaccountoption import TargetAccountOption
from codat_bankfeeds.models.update_connection import UpdateConnection
from codat_bankfeeds.models.shared.validation import Validation
from codat_bankfeeds.models.shared.validationitem import ValidationItem
