"""codat_bankfeeds.models.operations.create_connection — re-export of the create_connection operation envelope."""

from codat_bankfeeds.api.connections import CreateConnectionRequest
from codat_bankfeeds.models.create_connection_request import CreateConnectionRequest as CreateConnectionRequestBody
from codat_bankfeeds.models.create_connection_request import CreateConnectionRequestTypedDict as CreateConnectionRequestBodyTypedDict
from codat_bankfeeds.api.connections import CreateConnectionRequestTypedDict
