from __future__ import annotations
from typing import Union
from typing_extensions import TypeAliasType
from codat_bankfeeds.models.shared.sourceaccountv2batchcreateresponse import SourceAccountV2BatchCreateResponseTypedDict
from codat_bankfeeds.models.shared.sourceaccountbatchcreateresponse import SourceAccountBatchCreateResponseTypedDict
from codat_bankfeeds.models.shared.sourceaccountbatcherrorresponse import SourceAccountBatchErrorResponseTypedDict

CreateBatchSourceAccountResponseBodyTypedDict = TypeAliasType("CreateBatchSourceAccountResponseBodyTypedDict", Union[SourceAccountV2BatchCreateResponseTypedDict, SourceAccountBatchCreateResponseTypedDict, SourceAccountBatchErrorResponseTypedDict])
