"""codat_bankfeeds.models.operations.get_latest_managed_bank_feed_sync — re-export of the get_latest_managed_bank_feed_sync operation envelope."""

from codat_bankfeeds.api.managed_bank_feeds import GetLatestManagedBankFeedSyncRequest
from codat_bankfeeds.api.managed_bank_feeds import GetLatestManagedBankFeedSyncRequestTypedDict
