"""codat_bankfeeds.models.operations.unlink_connection — re-export of the unlink_connection operation envelope."""

from codat_bankfeeds.api.connections import UnlinkConnectionRequest
from codat_bankfeeds.api.connections import UnlinkConnectionRequestTypedDict
from codat_bankfeeds.models.update_connection import UpdateConnection as UnlinkConnectionUpdateConnection
from codat_bankfeeds.models.update_connection import UpdateConnectionTypedDict as UnlinkConnectionUpdateConnectionTypedDict
